"use client";
import Link from "next/link";
import {useState} from "react";
type Msg={role:"user"|"assistant";text:string};
export default function Assistant(){
 const [input,setInput]=useState(""); const [loading,setLoading]=useState(false);
 const [messages,setMessages]=useState<Msg[]>([{role:"assistant",text:"I'm here. What's going on?"}]);
 async function send(){const q=input.trim();if(!q||loading)return;const next=[...messages,{role:"user" as const,text:q}];setMessages(next);setInput("");setLoading(true);try{const r=await fetch("/api/chat",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({messages:next})});const d=await r.json();setMessages(m=>[...m,{role:"assistant",text:d.text||d.error||"I couldn't respond right now. Please try again."}])}catch{setMessages(m=>[...m,{role:"assistant",text:"I couldn't connect right now. Please try again."}])}finally{setLoading(false)}}
 return <main className="coachChat"><aside className="coachSide"><Link href="/" className="coachBrand"><img className="nachyFaceLogo" src="/nachyai-logo.svg" alt="NachyAI" /><span className="coachBrandName">Nachy<span>AI</span></span><small>Here for you.</small></Link><button className="newChat" onClick={()=>setMessages([{role:"assistant",text:"I'm here. What's going on?"}])}>＋ New conversation</button><nav><Link href="/">⌂ Home</Link><a className="active">◯ Chat</a><a>◎ Goals</a><a>▤ Library</a><a>⚙ Settings</a></nav><p className="coachSideNote">NachyAI can help you think, plan, write, learn, and work through everyday challenges.</p></aside><section className="coachConversation"><header className="coachHeader"><div><b>NachyAI</b><small>{loading?"Thinking…":"AI life assistant"}</small></div><span>•••</span></header><div className="coachMessages">{messages.map((m,i)=><div key={i} className={"coachMessage "+m.role}>{m.role==="assistant"&&<span className="coachAvatar"><img className="nachyFaceLogo" src="/nachyai-logo.svg" alt="NachyAI" /></span>}<p>{m.text}</p></div>)}{loading&&<div className="coachMessage assistant"><span className="coachAvatar"><img className="nachyFaceLogo" src="/nachyai-logo.svg" alt="NachyAI" /></span><p>Thinking…</p></div>}</div><div className="coachBottom"><div className="coachSuggestions"><button onClick={()=>setInput("I need advice about something")}>I need advice</button><button onClick={()=>setInput("Help me make a plan")}>Make a plan</button><button onClick={()=>setInput("Help me make a decision")}>Help me decide</button></div><div className="coachComposer"><button>＋</button><textarea value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();send()}}} placeholder="Message NachyAI..." disabled={loading}/><button title="Voice">◉</button><button className="sendCoach" onClick={send} disabled={loading}>↑</button></div><small>NachyAI can make mistakes. For important decisions, verify information.</small></div></section></main>
}