import Link from "next/link";
const actions=[["💬","Life Guidance","Get clarity, perspective, and practical next steps."],["🎯","Goals & Planning","Turn your ideas into action with step-by-step plans."],["💡","Problem Solving","Work through any challenge, big or small."],["📝","Writing Help","Emails, documents, resumes, messages and more."],["🎓","Learn New Things","Get simple explanations and personalized learning."],["♥","Just Talk","A judgment-free space to be yourself."]];
const topics=["Motivation","Productivity","Relationships","Work & Career","Stress & Wellness","Health & Habits"];
export default function Home(){return <main className="lifeApp">
<aside className="lifeSide"><Link href="/" className="lifeLogo"><img className="nachyFaceLogo" src="/nachyai-logo.svg" alt="NachyAI" /><strong>Nachy<span>AI</span></strong><small>Here for you.</small></Link><nav className="lifeSideNav"><a className="active">⌂ <span>Home</span></a><Link href="/assistant">▢ <span>Chat</span></Link><a>◎ <span>Goals</span></a><a>⊞ <span>Tools</span></a><a>▤ <span>Library</span></a><a>♙ <span>Profile</span></a><a>⚙ <span>Settings</span></a></nav><div className="lifeQuote">“A better tomorrow starts with a conversation today.”</div><button className="lifePro">♛ Upgrade to Pro</button></aside>
<section className="lifeMain"><header className="lifeTop"><nav><a>Features</a><a>Pricing</a><a>About</a><a>FAQ</a></nav><div className="lifeProfile"><span>☾</span><b>NJ</b><small>Good to see you,<strong>Nicholas</strong></small></div></header>
<section className="lifeHero"><div className="heroShade"/><div className="lifeHeroCopy"><p>NACHYAI</p><h1>Whatever you're facing,<br/>you don't have to<br/>figure it out alone.</h1><h2>Talk through a problem. Make a plan. Get something done.<br/>Or just talk. I'm here for you.</h2></div></section>
<section className="lifeContent"><Link href="/assistant" className="lifePrompt"><div><b>What's going on?</b><span>Type a message or click the mic to talk...</span></div><div className="promptTools"><span>＋</span><span>⌕</span><span>▧</span><span>◎</span><button>🎙</button><button>↑</button></div></Link>
<div className="lifePills"><Link href="/assistant">💬 I need advice</Link><Link href="/assistant">◈ Help me decide</Link><Link href="/assistant">▣ Make a plan</Link><Link href="/assistant">♥ I need to talk</Link><Link href="/assistant">⚡ Help me get something done</Link></div>
<div className="lifeCards">{actions.map(([i,t,d])=><Link href="/assistant" key={t}><i>{i}</i><div><b>{t}</b><p>{d}</p></div></Link>)}</div>
<h3 className="topicTitle">Popular Topics</h3><div className="lifeTopics">{topics.map((t,i)=><Link href="/assistant" key={t}><div className={"topicArt t"+i}></div><b>{t}</b><small>{["I feel stuck...","Help me get organized.","I need a different perspective.","Help with my job or business.","I just need to talk.","Help me build better habits."][i]}</small></Link>)}</div>
<footer className="lifeFooter"><span>∞ &nbsp; Powered by leading AI models</span><span>▣ &nbsp; Your privacy matters</span><span>♢ &nbsp; Built for real life</span><span>♟ &nbsp; Always here for you</span></footer></section></section></main>}